services:
  postgres:
    image: postgres:16
    container_name: infrawatch_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: infrawatch
      POSTGRES_USER: infrawatch_user
      POSTGRES_PASSWORD: infrawatch_password
    ports:
      - "5432:5432"
    volumes:
      - infrawatch_postgres_data:/var/lib/postgresql/data

volumes:
  infrawatch_postgres_data:
