services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: infrawatch_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: "${DB_DATABASE:-infrawatch}"
      DB_USERNAME: "${DB_USERNAME:-infrawatch_user}"
      DB_PASSWORD: "${DB_PASSWORD:?Define DB_PASSWORD in .env.docker}"
      CACHE_STORE: array
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      TELEGRAM_ENABLED: false
      MONITORING_HISTORY_RETENTION_DAYS: 30
      BROADCAST_CONNECTION: reverb
      REVERB_APP_ID: "${REVERB_APP_ID:?Define REVERB_APP_ID in .env.docker}"
      REVERB_APP_KEY: "${REVERB_APP_KEY:?Define REVERB_APP_KEY in .env.docker}"
      REVERB_APP_SECRET: "${REVERB_APP_SECRET:?Define REVERB_APP_SECRET in .env.docker}"
      REVERB_HOST: reverb
      REVERB_PORT: 8080
      REVERB_SCHEME: http
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      composer install &&
      php artisan key:generate --force &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000 --no-reload
      "

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: infrawatch_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: "${DB_DATABASE:-infrawatch}"
      DB_USERNAME: "${DB_USERNAME:-infrawatch_user}"
      DB_PASSWORD: "${DB_PASSWORD:?Define DB_PASSWORD in .env.docker}"
      CACHE_STORE: array
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      TELEGRAM_ENABLED: false
      MONITORING_HISTORY_RETENTION_DAYS: 30
      BROADCAST_CONNECTION: reverb
      REVERB_APP_ID: "${REVERB_APP_ID:?Define REVERB_APP_ID in .env.docker}"
      REVERB_APP_KEY: "${REVERB_APP_KEY:?Define REVERB_APP_KEY in .env.docker}"
      REVERB_APP_SECRET: "${REVERB_APP_SECRET:?Define REVERB_APP_SECRET in .env.docker}"
      REVERB_HOST: reverb
      REVERB_PORT: 8080
      REVERB_SCHEME: http
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started
    command: >
      sh -c "
      composer install &&
      php artisan schedule:work
      "

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: infrawatch_queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: "${DB_DATABASE:-infrawatch}"
      DB_USERNAME: "${DB_USERNAME:-infrawatch_user}"
      DB_PASSWORD: "${DB_PASSWORD:?Define DB_PASSWORD in .env.docker}"
      CACHE_STORE: array
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      TELEGRAM_ENABLED: false
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started
    command: >
      sh -c "
      composer install &&
      php artisan queue:work --sleep=3 --tries=3
      "
    profiles:
      - queue

  postgres:
    image: postgres:16
    container_name: infrawatch_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${DB_DATABASE:-infrawatch}"
      POSTGRES_USER: "${DB_USERNAME:-infrawatch_user}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?Define DB_PASSWORD in .env.docker}"
    ports:
      - "5432:5432"
    volumes:
      - infrawatch_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
          [
            "CMD-SHELL",
            "pg_isready -U ${DB_USERNAME:-infrawatch_user} -d ${DB_DATABASE:-infrawatch}"
          ]
      interval: 10s
      timeout: 5s
      retries: 5
  reverb:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: infrawatch_reverb
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true

      BROADCAST_CONNECTION: reverb
      REVERB_APP_ID: "${REVERB_APP_ID:?Define REVERB_APP_ID in .env.docker}"
      REVERB_APP_KEY: "${REVERB_APP_KEY:?Define REVERB_APP_KEY in .env.docker}"
      REVERB_APP_SECRET: "${REVERB_APP_SECRET:?Define REVERB_APP_SECRET in .env.docker}"
      REVERB_HOST: reverb
      REVERB_PORT: 8080
      REVERB_SCHEME: http
      REVERB_SERVER_HOST: 0.0.0.0
      REVERB_SERVER_PORT: 8080

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: "${DB_DATABASE:-infrawatch}"
      DB_USERNAME: "${DB_USERNAME:-infrawatch_user}"
      DB_PASSWORD: "${DB_PASSWORD:?Define DB_PASSWORD in .env.docker}"

      CACHE_STORE: array
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      TELEGRAM_ENABLED: false
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started
    command: >
      sh -c "
      composer install &&
      php artisan reverb:start --host=0.0.0.0 --port=8080
      "
volumes:
  infrawatch_postgres_data:
